name: build
on:
  push:
    branches: [ "main", "develop", "dev/**" ]
  pull_request:
    branches: [ "main", "develop", "dev/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - run: chmod +x ./gradlew

      - name: Clean build
        run: ./gradlew clean build

      - name: Upload Fabric Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Fabric Artifacts
          path: fabric/build/libs

      - name: Upload Forge Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Forge Artifacts
          path: forge/build/libs