name: Build and Publish
on:
  push:
    branches: [ "dev/**", "fix/**" ]
  pull_request:
    branches: [ "dev/**", "fix/**" ]
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to Modrinth and CurseForge
        required: true
        default: "false"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@6712f98d592b126629afd27dc4870c93b53426b4
        with:
          java: 21

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Prepare Changelog
        run: ./gradlew -q prepareChangelog > prepared_changelog.md

      - name: Capture Fabric Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-fabric
          path: fabric/build/libs

      - name: Capture Forge Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-forge
          path: forge/build/libs

      - name: Capture Changelog
        uses: actions/upload-artifact@v4
        with:
          name: build-changelog
          path: prepared_changelog.md

  publish:
    if: ${{ github.event.inputs.publish }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Fabric artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/fabric
          pattern: build-fabric
          merge-multiple: true

      - name: Download Forge artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/forge
          pattern: build-forge
          merge-multiple: true

      - name: Download Changelog
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: build-changelog

      - name: List build artifacts
        run: ls -R build

      - name: Show Changelog
        run: cat build-changelog/prepared_changelog.md

      - name: Get Version and Platform
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./gradle.properties"
          properties: "version enabledPlatforms minecraftVersion"

      - name: Upload Forge Releases (GitHub)
        id: forge_release
        if: contains(steps.properties.outputs.enabledPlatforms, 'forge')
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: ./build/forge/!(*-@(dev|sources|dev-shadow)).jar
          name: "AstralBot ${{ steps.properties.outputs.version }} Forge ${{ steps.properties.output.minecraftVersion }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: build-changelog/prepared_changelog.md
          loaders: forge
          game-versions: ${{ steps.properties.outputs.minecraftVersion }}

      - name: Upload Fabric Releases (GitHub)
        id: fabric_release
        if: contains(steps.properties.outputs.enabledPlatforms, 'fabric')
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: ./build/fabric/!(*-@(dev|sources|dev-shadow)).jar
          name: "AstralBot ${{ steps.properties.outputs.version }} Fabric ${{ steps.properties.output.minecraftVersion }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: build-changelog/prepared_changelog.md
          loaders: fabric
          game-versions: ${{ steps.properties.outputs.minecraftVersion }}
