name: Build
on:
  push:
    branches: [ "dev/**" ]

permissions:
  contents: write

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: null2264/actions/gradle-setup@6712f98d592b126629afd27dc4870c93b53426b4
        with:
          java: 21
          gradle-no-cache-if: 'true'

      - name: Build with Gradle and generate dependency Graph
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dependencies
          dependency-graph: 'generate-and-submit'